name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: swift build -v
    - name: Test Package
      run: swift test -v
    # - name: Test Podfile
    #   run: ./testPodsec.sh
